### PR TITLE
Add non relative path module resolution

### PR DESCRIPTION
**Pull request by gaber85**
Added the non-relative module resolution stuff and change the import paths accordingly.

Just a couple of overall comments and suggestions to be consistent on:

- ditch default exports unless it’s the only way it gets consumed
- dropping I from interfaces
- dropping hyphens from filenames - stick with camelcase or pascal case for components
- avoid using matching dir and file names i.e. App/App

### CODE REVIEW

**Comment by sam-hunt** [comment]
image

I'm having trouble building this on my machine unfortunately. Is there perhaps another step which needs to happen somewhere?

**Comment by gaber85** [comment]
Did you purge your node modules and npm install?

**Comment by sam-hunt** [comment]
>Did you purge your node modules and npm install?

Just did now, and no dice unfortunately. Once working, wouldn't this create an ambiguity, say if we used a subpath export from a package called [components](https://www.npmjs.com/package/components) etc?

**Comment by gaber85** [comment]
Alright I've merged master again and fixed the issue. Give it ago @sam-hunt

**Review by sam-hunt — APPROVED** [review]
Looks good

**Pull request merged**
